# Generated by Django 2.2 on 2019-05-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(default='unnamed', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='doctor',
            field=models.CharField(default='unnamed', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='insurance',
            field=models.CharField(max_length=20),
        ),
    ]
