# Generated by Django 2.2 on 2019-05-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20190506_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='insurance',
            field=models.CharField(default='unnamed', max_length=200),
        ),
    ]
