# Generated by Django 2.2 on 2019-05-08 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='invoice.Doctor'),
        ),
    ]
