# Generated by Django 2.2 on 2019-05-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20190508_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.ForeignKey(default='unnamed', on_delete=django.db.models.deletion.CASCADE, to='invoice.Client'),
        ),
    ]
