# Generated by Django 2.2 on 2019-05-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20190508_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='insurance',
        ),
    ]
