# Generated by Django 2.2.1 on 2019-05-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_invoice_insurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='client_name',
            new_name='client',
        ),
    ]
