# Generated by Django 2.2 on 2019-05-09 01:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20190508_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='available appointment date')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pub_date',
            field=models.ForeignKey(default=datetime.datetime(2019, 5, 9, 1, 27, 23, 293457), on_delete=django.db.models.deletion.CASCADE, to='invoice.Appointment'),
        ),
    ]
