# Generated by Django 2.2 on 2019-05-09 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20190509_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pub_date',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='invoice.Appointment'),
        ),
    ]
