# Generated by Django 2.2 on 2019-05-09 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20190509_0133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
