# Generated by Django 2.2.1 on 2019-05-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20190509_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='invoice_name',
        ),
    ]
